# Generated by Django 4.2.7 on 2023-11-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_rename_creator_boardgame_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.TextField(),
        ),
    ]
