# Generated by Django 4.2.7 on 2023-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_alter_boardgame_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='developer',
            field=models.CharField(default='Developer', max_length=255),
            preserve_default=False,
        ),
    ]
